# docker-compose.yml

version: '3.8'

services:
  aem-qa-db:
    image: mongo:7.0
    container_name: aem_qa_mongo_db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - aem-qa-net
    # ▼▼▼▼▼ 핵심 변경 사항 ▼▼▼▼▼
    volumes:
      # './data/mongodb_data' 대신 'mongodb-data'라는 이름의 볼륨 사용
      - mongodb-data:/data/db

networks:
  aem-qa-net:
    driver: bridge

# ▼▼▼ Docker가 관리할 볼륨을 새로 정의 ▼▼▼
volumes:
  mongodb-data: